import { ost_1 } from "../assets/audios"
import { hc1, hc3, hc5, hc6, hc8, xl1, xl3, xl5, xl7, xl8, xl9 } from "../assets/images"

export const recipes = [
    {
        id: 1,
        name: "ខបង្គា",
        image: xl3,
        description: "A delicious dish inspired by the character Xie Lian from the novel 'Tian Guan Ci Fu'. This dish is a fusion of flavors and textures, perfect for any occasion.",
        ingredients: [ 'Shrimp', 'Brown Sugar', 'Chicken Powder', 'Fish Sauce', 'Garlic', 'Scallion' ],
        instructions: [ 'wash shrimp with salt', 'put water and brown sugar add heat until sugar turn thick and golden', 'add water and put shrimp' ],
        prepTime: "30 minutes",
        cookTime: "1 hour",
        servings: 4,
        cuisine: "Chinese",
        dietaryRestrictions: ["Vegetarian"],
        nutrition: {
            calories: 300,
            protein: 10,
            fat: 5,
            carbohydrates: 50,
            fiber: 5,                       
        },
    },
    {
        id: 2,
        name: "ឆាស្ពៃ",
        image: xl9,
        description: "A delicious dish inspired by the character Xie Lian from the novel 'Tian Guan Ci Fu'.",
        ingredients: ['Spinach', 'Salt', 'Oyster Sauce', 'Sugar'],
        instructions: [ 'wash shrimp with salt', 'put water and brown sugar add heat until sugar turn ' ],
        prepTime: "30 minutes",
        cookTime: "1 hour",
        servings: 4,
        cuisine: "Chinese",
        dietaryRestrictions: ["Vegetarian"],
        nutrition: {
            calories: 300,
            protein: 10,
            fat: 5,
            carbohydrates: 50,
            fiber: 5,                       
        },
    },
    {
        id: 3,
        name: "ស្ងោរចាប់ឆាយ",
        image: xl1,
        description: "A delicious dish inspired by the character Xie Lian from the novel 'Tian Guan Ci Fu'.",
        ingredients: ['Crab', 'Garlic', 'Chili', 'Lime', 'Coriander', 'Salt'],
        instructions: ['clean crab', 'marinate with garlic, chili, lime, and salt', 'grill until cooked through'],
        prepTime: "30 minutes",
        cookTime: "1 hour",
        servings: 4,
        cuisine: "Chinese",
        dietaryRestrictions: ["Vegetarian"],
        nutrition: {
            calories: 300,
            protein: 10,
            fat: 5,
            carbohydrates: 50,
            fiber: 5,                       
        },
    },
    {
        id: 4,
        name: "ស៊ុបក្តាម",
        image: xl8,
        description: "A delicious dish inspired by the character Xie Lian from the novel 'Tian Guan Ci Fu'.",
        ingredients: ['Crab', 'Garlic', 'Chili', 'Lime', 'Coriander', 'Salt'],
        instructions: ['clean crab', 'marinate with garlic, chili, lime, and salt', 'grill until cooked through'],
        prepTime: "30 minutes",
        cookTime: "1 hour",
        servings: 4,
        cuisine: "Chinese",
        dietaryRestrictions: ["Vegetarian"],
        nutrition: {
            calories: 300,
            protein: 10,
            fat: 5,
            carbohydrates: 50,
            fiber: 5,                       
        },
    },
    {
        id: 5,
        name: "ត្រីឆា​ពិសេស",
        image: hc5,
        description: "A spicy grilled fish dish with rich flavors of garlic and herbs.",
        ingredients: ['Fish', 'Garlic', 'Chili', 'Lime', 'Coriander', 'Salt'],
        instructions: ['clean fish', 'marinate with garlic, chili, lime, and salt', 'grill until cooked through'],
        prepTime: "20 minutes",
        cookTime: "25 minutes",
        servings: 2,
        cuisine: "Cambodian",
        dietaryRestrictions: [],
        nutrition: {
            calories: 250,
            protein: 30,
            fat: 10,
            carbohydrates: 5,
            fiber: 2,
        },
    },
    {
        id: 6,
        name: "នំ​ប៉ុងកូកូណាត់",
        image: xl7,
        description: "Soft and chewy coconut cookies, perfect for dessert.",
        ingredients: ['Flour', 'Sugar', 'Butter', 'Egg', 'Coconut', 'Baking Powder'],
        instructions: ['mix flour, sugar, and baking powder', 'add butter and egg', 'fold in coconut and bake'],
        prepTime: "15 minutes",
        cookTime: "20 minutes",
        servings: 12,
        cuisine: "Dessert",
        dietaryRestrictions: ["Vegetarian"],
        nutrition: {
            calories: 120,
            protein: 2,
            fat: 6,
            carbohydrates: 15,
            fiber: 1,
        },
    },
    {
        id: 7,
        name: "កាហ្វេ​ម៉ូកា",
        image: hc3,
        description: "Rich and creamy mocha coffee, perfect for an afternoon pick-me-up.",
        ingredients: ['Coffee', 'Milk', 'Chocolate Syrup', 'Sugar', 'Whipped Cream'],
        instructions: ['brew coffee', 'mix with chocolate syrup and milk', 'top with whipped cream'],
        prepTime: "5 minutes",
        cookTime: "5 minutes",
        servings: 1,
        cuisine: "Beverage",
        dietaryRestrictions: ["Vegetarian"],
        nutrition: {
            calories: 180,
            protein: 6,
            fat: 5,
            carbohydrates: 28,
            fiber: 2,
        },
    },
    {
        id: 8,
        name: "បុក​ឆ្ងាញ់",
        image: xl5,
        description: "Classic stir-fried noodles with a savory soy-based sauce.",
        ingredients: ['Noodles', 'Soy Sauce', 'Garlic', 'Carrot', 'Cabbage', 'Oil'],
        instructions: ['cook noodles', 'stir fry garlic and vegetables', 'add noodles and soy sauce and toss'],
        prepTime: "10 minutes",
        cookTime: "15 minutes",
        servings: 2,
        cuisine: "Asian",
        dietaryRestrictions: ["Vegetarian"],
        nutrition: {
            calories: 300,
            protein: 8,
            fat: 10,
            carbohydrates: 45,
            fiber: 5,
        },
    },
    {
        id: 9,
        name: "ស្លាប​ក្រពើ​ឆា",
        image: hc1,
        description: "Crispy fried chicken wings with a hint of garlic and pepper.",
        ingredients: ['Chicken Wings', 'Garlic', 'Salt', 'Pepper', 'Oil'],
        instructions: ['season wings with garlic, salt, and pepper', 'deep fry until golden brown', 'serve hot'],
        prepTime: "15 minutes",
        cookTime: "20 minutes",
        servings: 3,
        cuisine: "American",
        dietaryRestrictions: [],
        nutrition: {
            calories: 400,
            protein: 25,
            fat: 30,
            carbohydrates: 5,
            fiber: 0,
        },
    },
    {
        id: 10,
        name: "កាឡៃ​ត្រី​សំពៅ",
        image: hc6,
        description: "Steamed fish with ginger and soy sauce, light and flavorful.",
        ingredients: ['Fish', 'Ginger', 'Soy Sauce', 'Spring Onion', 'Sesame Oil'],
        instructions: ['place fish on plate', 'top with ginger and spring onion', 'steam and pour soy sauce before serving'],
        prepTime: "10 minutes",
        cookTime: "15 minutes",
        servings: 2,
        cuisine: "Chinese",
        dietaryRestrictions: [],
        nutrition: {
            calories: 220,
            protein: 28,
            fat: 8,
            carbohydrates: 4,
            fiber: 1,
        },
    },
    {
        id: 11,
        name: "ប៉ោតាទ់​ព្រីហ្ស",
        image: hc8,
        description: "Crispy and golden potato fries, perfect as a snack or side dish.",
        ingredients: ['Potato', 'Salt', 'Oil', 'Paprika'],
        instructions: ['cut potatoes into sticks', 'fry in hot oil until golden', 'sprinkle with salt and paprika'],
        prepTime: "10 minutes",
        cookTime: "15 minutes",
        servings: 2,
        cuisine: "Snack",
        dietaryRestrictions: ["Vegan"],
        nutrition: {
            calories: 250,
            protein: 3,
            fat: 12,
            carbohydrates: 35,
            fiber: 3,
        },
    }
]

export const playlists = [
    {
        id: 1,
        name: "Xie Lian Playlist",
        src: ost_1,

    }
]